### ISSUE TITLE
Always get "Error: Invalid hook call." builds

### ISSUE THREAD

**Issue by milesj** [Rowno/react-benchmark#17]
I started implementing this library here (https://github.com/aesthetic-suite/benchmarks/commit/d8d48e15d5c1433d712ddf1927b069f1c3d7e605) to benchmark React (obviously). As seen from the PR, the test case is really really simple but it always errors with:

```
ERROR: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (http://localhost:52712/bundle.js:50359:13)
    at useMemo (http://localhost:52712/bundle.js:50414:20)
    at Aesthetic (http://localhost:52712/bundle.js:105:69)
    at Module../client.js (http://localhost:52712/bundle.js:52213:135)
    at __webpack_require__ (http://localhost:52712/bundle.js:20:30)
    at http://localhost:52712/bundle.js:84:18
    at http://localhost:52712/bundle.js:87:10
```

I've verified the node module tree AND the webpack bundle only has 1 copy of react, but I cannot figure this out. It fails on the `useMemo` hook, but runs if I remove it, which makes no sense since I'm using it correctly.

Hoping you may have a little more insight, cheers.

**Comment by milesj** [comment]
I figured it out. I need to export a function that _returns_ a component, not export the component declaration

```
export default () => <Aesthetic />;
```

I feel like the docs should explain this a little bit better.
