### ISSUE TITLE
Parser fails on jsx syntax

### ISSUE THREAD

**Issue by jeroenptrs** [Rowno/react-benchmark#5]
The benchmarker fails if it's pointed to any component (JSX or React) :(

Stacktrace:
````✖ Compiling bundle
/Users/jeroen.peeters/Documents/tools/benchmarks/box.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jeroen.peeters/Documents/tools/benchmarks/box.js: Unexpected token (4:9)

  2 |
  3 | export default function benchmark () {
> 4 |   return <div />;
    |          ^
  5 | }
  6 |
    at Parser.raise (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:6322:17)
    at Parser.unexpected (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:7638:16)
    at Parser.parseExprAtom (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:8799:20)
    at Parser.parseExprSubscripts (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:8385:23)
    at Parser.parseMaybeUnary (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:8365:21)
    at Parser.parseExprOps (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:8252:23)
    at Parser.parseMaybeConditional (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:8225:23)
    at Parser.parseMaybeAssign (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:8172:21)
    at Parser.parseExpression (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:8120:23)
    at Parser.parseReturnStatement (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:10132:28)
    at Parser.parseStatementContent (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:9811:21)
    at Parser.parseStatement (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:9763:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:10340:25)
    at Parser.parseBlockBody (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:10327:10)
    at Parser.parseBlock (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:10311:10)
    at Parser.parseFunctionBody (/Users/jeroen.peeters/.nvm/versions/node/v8.16.0/lib/node_modules/react-benchmark/node_modules/@babel/parser/lib/index.js:9382:24)
 @ ./client.js 4:0-59 13:16-29 21:20-33``

**Comment by Rowno** [comment]
It looks like your target file doesn't have any [Babel config](https://babeljs.io/docs/en/config-files) in it's directory or a parent directory, so Babel isn't actually doing anything.

**Comment by pedroapfilho** [comment]
Actually, it happens with create-react-app too, is it possible to add support for it?

**Comment by Rowno** [comment]
react-benchmark does support JSX, you just need to have a Babel config in your repo that includes @babel/preset-react.
